 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rare_fishes", type: :request do
  
  # RareFish. As you add validations to RareFish, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RareFish.create! valid_attributes
      get rare_fishes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rare_fish = RareFish.create! valid_attributes
      get rare_fish_url(rare_fish)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rare_fish_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rare_fish = RareFish.create! valid_attributes
      get edit_rare_fish_url(rare_fish)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RareFish" do
        expect {
          post rare_fishes_url, params: { rare_fish: valid_attributes }
        }.to change(RareFish, :count).by(1)
      end

      it "redirects to the created rare_fish" do
        post rare_fishes_url, params: { rare_fish: valid_attributes }
        expect(response).to redirect_to(rare_fish_url(RareFish.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RareFish" do
        expect {
          post rare_fishes_url, params: { rare_fish: invalid_attributes }
        }.to change(RareFish, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rare_fishes_url, params: { rare_fish: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rare_fish" do
        rare_fish = RareFish.create! valid_attributes
        patch rare_fish_url(rare_fish), params: { rare_fish: new_attributes }
        rare_fish.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rare_fish" do
        rare_fish = RareFish.create! valid_attributes
        patch rare_fish_url(rare_fish), params: { rare_fish: new_attributes }
        rare_fish.reload
        expect(response).to redirect_to(rare_fish_url(rare_fish))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rare_fish = RareFish.create! valid_attributes
        patch rare_fish_url(rare_fish), params: { rare_fish: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rare_fish" do
      rare_fish = RareFish.create! valid_attributes
      expect {
        delete rare_fish_url(rare_fish)
      }.to change(RareFish, :count).by(-1)
    end

    it "redirects to the rare_fishes list" do
      rare_fish = RareFish.create! valid_attributes
      delete rare_fish_url(rare_fish)
      expect(response).to redirect_to(rare_fishes_url)
    end
  end
end
